[workspace]

members = [

    "freja-parser",
    "freja-vm",
    #"freja-ast",
    #"freja-evaluator",
    #"freja-runtime",
    "freja",
    #"freja-parser2"
]

[profile.release]
lto = true
panic = 'abort'
