[package]
name = "freja-interpreter"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]
freja-parser = { path = "../freja-parser" }

[[example]]
name = "interpreter"
path = "example/interpreter.rs"